name: flutter_alarm
description: A new Flutter project.


publish_to:
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter_speed_dial: ^6.0.0

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.2.0
  get: ^4.6.5
  flutter_time_picker_spinner: ^2.0.0
  android_alarm_manager_plus:
    git:
      url: https://github.com/jja08111/plus_plugins.git
      path: packages/android_alarm_manager_plus
      ref: alarm_app
  audioplayers: ^0.20.1
  json_annotation: ^4.5.0
  path_provider: ^2.0.11
  shared_preferences: ^2.0.15
  permission_handler: ^9.2.0
  provider: ^6.0.3
  sqflite: ^2.0.2+1
  path: ^1.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/sounds/alarmSound.mp3

fonts:
  - family: Roboto
    fonts:
      - assets: assets/fonts/Roboto/Roboto-Light.ttf
        weight: 300
      - assets: assets/fonts/Roboto/Roboto-Regular.ttf
        weight: 400
      - assets: assets/fonts/Roboto/Roboto-Medium.ttf
        weight: 500
      - assets: assets/fonts/Roboto/Roboto-Bold.ttf
        weight: 700
      - assets: assets/fonts/Roboto/Roboto-Black.ttf
        weight: 900
      - assets: assets/fonts/Roboto/Roboto-Thin.ttf

